version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/plugins/nbg-presentations/tools/nbg-presentation"
    schedule:
      interval: "weekly"
